# Generated by Django 2.1 on 2018-09-01 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('publication', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now=True)),
                ('return_date', models.DateField()),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocator.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocator.Member'),
        ),
    ]
