# Generated by Django 2.1 on 2018-09-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
