# Generated by Django 2.1 on 2018-09-01 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0002_book_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mob_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
