# Generated by Django 2.1 on 2018-09-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0003_member_mob_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
