# Generated by Django 2.1 on 2018-09-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0004_issue_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='returned',
        ),
    ]
